# Generated by Django 5.1 on 2024-09-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_customuser_date_birth_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="date_birth",
            field=models.DateField(blank=True, default="1403-06-12"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="register_date",
            field=models.DateField(default="1403-06-12"),
        ),
    ]
