# Generated by Django 5.1 on 2024-09-01 15:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="date",
            field=models.DateField(default="1403-06-11"),
        ),
        migrations.AlterField(
            model_name="order",
            name="time",
            field=models.TimeField(default="19:19:34"),
        ),
    ]
