# Generated by Django 5.1 on 2024-09-01 18:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_alter_order_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="time",
            field=models.TimeField(default="22:29:03"),
        ),
    ]
