# Generated by Django 5.1 on 2024-09-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0006_alter_order_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="time",
            field=models.TimeField(default="20:21:59"),
        ),
    ]
