# Generated by Django 5.1 on 2024-08-31 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("category", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("price", models.PositiveIntegerField()),
                ("count", models.IntegerField()),
                ("model", models.CharField(max_length=255)),
                ("main_photo", models.ImageField(upload_to="products/%Y/%m/%d/")),
                (
                    "photo1",
                    models.ImageField(blank=True, upload_to="products/%Y/%m/%d/"),
                ),
                (
                    "photo2",
                    models.ImageField(blank=True, upload_to="products/%Y/%m/%d/"),
                ),
                (
                    "photo3",
                    models.ImageField(blank=True, upload_to="products/%Y/%m/%d/"),
                ),
                (
                    "photo4",
                    models.ImageField(blank=True, upload_to="products/%Y/%m/%d/"),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="category.brand",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="category.category",
                    ),
                ),
                (
                    "is_favorited_by",
                    models.ManyToManyField(
                        blank=True,
                        related_name="favorite_products",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
