# Generated by Django 5.1 on 2024-09-01 18:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_product_seller"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="brand",
        ),
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
    ]
