# Generated by Django 5.1.2 on 2025-02-12 17:49

import order.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(default=order.models.generate_order_code, max_length=7, unique=True)),
                ('payment_type', models.CharField(choices=[('cash', 'نقد'), ('credit_card', 'درگاه پرداخت')], default='cash', max_length=20)),
                ('status', models.CharField(choices=[('canceled', 'کنسل'), ('successful', 'موفق'), ('pending', 'در انتظار پرداخت'), ('delivered', 'تحویل شده'), ('returned', 'مرجوع')], default='pending', max_length=20)),
                ('total_amount', models.PositiveIntegerField()),
                ('created_at_date', models.DateField(default='1403-11-24')),
                ('created_at_time', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('payment_method', models.CharField(choices=[('cash', 'نقد'), ('credit_card', 'درگاه پرداخت')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('failed', 'ناموفق')], default='pending', max_length=20)),
                ('transaction_ref_id', models.CharField(blank=True, max_length=100, null=True)),
                ('authority', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('price', models.PositiveIntegerField()),
            ],
        ),
    ]
