# Generated by Django 5.1.2 on 2025-02-12 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_initial'),
        ('product', '0003_remove_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='category.model'),
        ),
    ]
